# Generated by Django 3.2.8 on 2022-01-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(max_length=10)),
                ('jobtitle', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('applylink', models.CharField(max_length=100)),
            ],
        ),
    ]
