# Generated by Django 3.2.8 on 2022-01-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsforyou', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='eligibility',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='jobrole',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='lastdate',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='qualification',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='applylink',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobtitle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
