# Generated by Django 3.2.8 on 2022-01-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsforyou', '0003_alter_job_lastdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='applylink',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobid',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='lastdate',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(default='', max_length=50),
        ),
    ]
