# Generated by Django 3.2.8 on 2022-01-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsforyou', '0004_auto_20220110_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
